### ISSUE TITLE
The connection is not open

### ISSUE THREAD

**Issue by onuryurtturk** [EricADockery/ZebraPrinterDemo#2]
Hi Eric, I got connection is not open error.How can I handle this?

Error executing data writing Optional(Error Domain=ZSDK_API_ERROR_DOMAIN Code=0 "The connection is not open" UserInfo={NSLocalizedDescription=The connection is not open})

**Comment by EricADockery** [comment]
It sounds like the phone is not finding the printer on the connection / startup. I would put a breakpoint in the manager on the connect / disconnect methods and see if they are ever being hit. Also, there was an issue with a missing new line that has been updated now so that might have been causing the issue. I don't have access to a Printer anymore so maintaining the repo here is hard for me to do.

**Comment by deniztezcan** [comment]
@EricADockery I have the same problem. On my device the Zebra is visible as "connected" and via the zebra app I can manage the printer settings. However when I try to use the code, it never hits the "didConnect" or "didDisconnect" functions. When I print it gives me the same error as onur posted above.

**Comment by EricADockery** [comment]
Probably just my code then. Feel free to adjust or just use this as a reference. I don't have a Printer anymore so I can't really troubleshoot. I know at one point this worked.

**Comment by willm132** [comment]
@onuryurtturk @deniztezcan  @EricADockery I have submitted a pull request to fix your issues

**Comment by EricADockery** [comment]
@willm132 thanks! merged it in.
